config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/confirm_tos' => 'sessions#confirm_tos', as: :confirm_tos, via: :patch
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users, except: :destroy do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      get :search
    end
    member do
      put :password
      get :output
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index do
    collection { get :search}
  end
  resources :characters do
    resources :aliases, only: [:new, :create, :destroy]
    member do
      get :replace
      post :do_replace
      post :duplicate
    end
    collection do
      get :search
      get :facecasts
    end
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
    collection { get :search}
  end

  # Forums
  resources :boards do
    collection do
      post :mark
      get :search
    end
  end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :delete_history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member do
      get :history
      post :restore
    end
    collection { get :search }
  end
  resources :tags, except: [:new, :create]

  # Indexes
  resources :indexes
  resources :index_sections, except: [:index]
  resources :index_posts, only: [:new, :create, :edit, :update, :destroy]

  # Blocks
  resources :blocks, except: [:show]

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index, :show] do
        member { get :posts }
      end
      resources :board_sections, only: [] do
        collection { post :reorder }
      end
      resources :characters, only: [:index, :show, :update] do
        collection { post :reorder }
      end
      resources :galleries, only: :show
      resources :icons, only: [] do
        collection { post :s3_delete }
      end
      resources :index_posts, only: [] do
        collection { post :reorder }
      end
      resources :index_sections, only: [] do
        collection { post :reorder }
      end
      resources :posts, only: [:index, :show] do
        resources :replies, only: :index
        collection { post :reorder }
      end
      resources :tags, only: [:index, :show]
      resources :templates, only: :index
      resources :users, only: :index do
        member { get :posts }
      end
    end
  end

  # Legalese
  match '/tos' => 'about#tos', as: :tos, via: :get
  match '/privacy' => 'about#privacy', as: :privacy, via: :get
  match '/contact' => 'about#contact', as: :contact, via: :get
  match '/dmca' => 'about#dmca', as: :dmca, via: :get

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :news
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount Resque::Server.new, :at => "/resque_web"
end

app/models/user.rb
class User < ApplicationRecord
  include Blockable
  include Presentable
  include Permissible

  MIN_USERNAME_LEN = 3
  MAX_USERNAME_LEN = 80
  CURRENT_TOS_VERSION = 20181109
  RESERVED_NAMES = ['(deleted user)', 'Glowfic Constellation']

  attr_accessor :password, :password_confirmation
  attr_writer :validate_password

  has_many :icons
  has_many :characters
  has_many :galleries
  has_many :character_groups
  has_many :templates
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id', inverse_of: :sender
  has_many :messages, foreign_key: 'recipient_id', inverse_of: :recipient
  has_many :password_resets
  has_many :favorites
  has_many :favoriteds, as: :favorite, class_name: 'Favorite', inverse_of: :favorite
  has_many :posts
  has_many :replies
  has_many :indexes
  has_many :news
  has_one :report_view
  belongs_to :avatar, class_name: 'Icon', inverse_of: :user, optional: true
  belongs_to :active_character, class_name: 'Character', inverse_of: :user, optional: true

  validates :crypted, presence: true
  validates :email,
    presence: { on: :create },
    uniqueness: { allow_blank: true }
  validates :username,
    presence: true,
    uniqueness: true,
    length: { in: MIN_USERNAME_LEN..MAX_USERNAME_LEN, allow_blank: true }
  validates :password,
    length: { minimum: 6, if: :validate_password? },
    confirmation: { if: :validate_password? }
  validates :moiety, format: { with: /\A([0-9A-F]{3}){0,2}\z/i }
  validates :password, :password_confirmation, presence: { if: :validate_password? }
  validate :username_not_reserved

  before_validation :encrypt_password, :strip_spaces
  after_save :clear_password

  scope :ordered, -> { order(username: :asc) }
  scope :active, -> { where(deleted: false) }

  acts_as_taggable_on :settings, :labels, :content_warnings

  nilify_blanks

  def authenticate(password)
    return crypted == crypted_password(password) if salt_uuid.present?
    crypted == old_crypted_password(password)
  end

  def gon_attributes
    {
      :username            => username,
      :active_character_id => active_character_id,
      :avatar              => avatar.try(:as_json),
    }
  end

  def writes_in?(continuity)
    continuity.open_to?(self)
  end

  def galleryless_icons
    icons.where(has_gallery: false).ordered
  end

  def default_view
    super || 'icon'
  end

  def archive
    User.transaction do
      self.update!(email_notifications: false, deleted: true, favorite_notifications: false)
      self.taggings.destroy_all
      Block.where(blocking_user: self).or(Block.where(blocked_user: self)).destroy_all
    end
  end

  def visible_posts
    Rails.cache.fetch(PostViewer.cache_string_for(self.id), expires_in: 1.month) do
      PostViewer.where(user: self).pluck(:post_id)
    end
  end

  private

  def strip_spaces
    self.username = self.username.strip if self.username.present?
  end

  def encrypt_password
    if password.present?
      self.salt_uuid ||= SecureRandom.uuid
      self.crypted = crypted_password(password)
    end
  end

  def crypted_password(unencrypted)
    crypted = "Adding #{salt_uuid} to #{unencrypted}"
    17.times { crypted = Digest::SHA1.hexdigest(crypted) }
    crypted
  end

  def old_crypted_password(unencrypted)
    crypted = "Adding #{old_salt} to #{unencrypted}"
    17.times { crypted = Digest::SHA1.hexdigest(crypted) }
    crypted
  end

  def old_salt
    "1d0e9f00dc7#{username.to_s.downcase}dda7264ec524b051e434f4dda9ecfef8891004efe56fbff6a0"
  end

  def clear_password
    self.password = nil
    self.password_confirmation = nil
  end

  def validate_password?
    !!@validate_password
  end

  def username_not_reserved
    return unless self.username.present?
    return unless RESERVED_NAMES.include?(self.username)
    errors.add(:username, 'is invalid')
  end
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < Api::ApiController
  before_action :login_required, only: [:update, :reorder]
  before_action :find_character, except: [:index, :reorder]
  before_action :find_post, except: [:update, :reorder]
  before_action :find_template, only: :index
  before_action :find_user, only: :index
  before_action :require_permission, only: :update

  resource_description do
    description 'Viewing and editing characters'
  end

  api :GET, '/characters', 'Load all the characters that match the given query, results ordered by name'
  param :q, String, required: false, desc: "If provided, will return only characters where q is present as a substring anywhere in any of a character's name, screenname or template nickname."
  param :page, :number, required: false, desc: 'Page in results (25 per page)'
  param :post_id, :number, required: false, desc: 'If provided, will return only characters that appear in the provided post'
  param :user_id, :number, required: false, desc: 'If provided, will return only characters that belong to the provided user'
  param :template_id, :number, required: false, desc: 'If provided, will return only characters that belong to the provided template. Use 0 to find only characters with no template.'
  param :includes, Array, in: ["default_icon", "aliases", "template_name"], of: String, required: false, desc: 'Specify additional fields to return in JSON'
  error 403, "Post is not visible to the user"
  error 422, "Invalid parameters provided"
  def index
    queryset = Character.ordered
    queryset = queryset.with_name(params[:q].to_s) if params[:q].present?
    queryset = queryset.where(user_id: @user.id) if params[:user_id].present?
    queryset = queryset.where(template_id: @template&.id) if params[:template_id].present?

    if @post
      char_ids = @post.replies.select(:character_id).distinct.pluck(:character_id) + [@post.character_id]
      queryset = queryset.where(id: char_ids)
    end

    characters = paginate queryset, per_page: 25
    includes = [:selector_name] + (params[:includes] || []).map(&:to_sym)
    render json: {results: characters.as_json(include: includes)}
  end

  api :GET, '/characters/:id', 'Load a single character as a JSON resource'
  param :id, :number, required: true, desc: 'Character ID'
  param :post_id, :number, required: false, desc: 'If provided, will return an additional alias_id_for_post param to represent most recently used alias for this character in the provided post'
  error 403, "Post is not visible to the user"
  error 404, "Character not found"
  error 422, "Invalid parameters provided"
  def show
    render json: @character.as_json(include: [:galleries, :default_icon, :aliases], post_for_alias: @post)
  end

  api :PATCH, '/characters/:id', 'Update a given character'
  param :id, :number, required: true, desc: 'Character ID'
  error 401, "You must be logged in"
  error 403, "Character is not editable by the user"
  error 404, "Character not found"
  error 422, "Invalid parameters provided"
  def update
    render json: {data: @character.as_json(include: [:default_icon])} and return unless params[:character]

    errors = []
    if params[:character][:default_icon_id].present?
      errors << {message: "Default icon could not be found"} unless Icon.find_by_id(params[:character][:default_icon_id])
    end

    @character.assign_attributes(character_params)
    errors += @character.errors.full_messages.map { |msg| {message: msg} } unless @character.valid?
    render json: {errors: errors}, status: :unprocessable_entity and return unless errors.empty?

    @character.save!
    render json: @character.as_json(include: [:default_icon])
  end

  api :POST, '/characters/reorder', 'Update the order of galleries on a character. This is an unstable feature, and may be moved or renamed; it should not be trusted.'
  error 401, "You must be logged in"
  error 403, "Character is not editable by the user"
  error 404, "CharactersGallery IDs could not be found"
  error 422, "Invalid parameters provided"
  param :ordered_characters_gallery_ids, Array, allow_blank: false
  def reorder
    section_ids = params[:ordered_characters_gallery_ids].map(&:to_i).uniq
    sections = CharactersGallery.where(id: section_ids)
    sections_count = sections.count
    unless sections_count == section_ids.count
      missing_sections = section_ids - sections.pluck(:id)
      error = {message: "Some character galleries could not be found: #{missing_sections * ', '}"}
      render json: {errors: [error]}, status: :not_found and return
    end

    characters = Character.where(id: sections.select(:character_id).distinct.pluck(:character_id))
    unless characters.count == 1
      error = {message: 'Character galleries must be from one character'}
      render json: {errors: [error]}, status: :unprocessable_entity and return
    end

    character = characters.first
    access_denied and return unless character.editable_by?(current_user)

    CharactersGallery.transaction do
      sections = sections.sort_by {|section| section_ids.index(section.id) }
      sections.each_with_index do |section, index|
        next if section.section_order == index
        section.update(section_order: index)
      end

      other_sections = CharactersGallery.where(character_id: character.id).where.not(id: section_ids).ordered
      other_sections.each_with_index do |section, i|
        index = i + sections_count
        next if section.section_order == index
        section.update(section_order: index)
      end
    end

    render json: {characters_gallery_ids: CharactersGallery.where(character_id: character.id).ordered.pluck(:id)}
  end

  private

  def find_character
    @character = find_object(Character)
  end

  def find_post
    return unless params[:post_id].present?
    return unless (@post = find_object(Post, :post_id, :unprocessable_entity))
    access_denied unless @post.visible_to?(current_user)
  end

  def find_template
    return unless params[:template_id].present?
    return if params[:template_id] == '0' # used to filter for templateless characters, so @template should remain nil without find_object raising a missing template error
    @template = find_object(Template, :template_id, :unprocessable_entity)
  end

  def find_user
    return unless params[:user_id].present?
    @user = find_object(User, :user_id, :unprocessable_entity)
  end

  def require_permission
    access_denied unless @character.user == current_user
  end

  def character_params
    params.fetch(:character, {}).permit(:default_icon_id, :name, :template_name, :screenname, :setting, :template_id, :pb, :description, gallery_ids: [])
  end
end

app/helpers/character_helper.rb
module CharacterHelper
  def settings_info(characters)
    settings = characters.joins(:settings).group(:id)
    sql = Arel.sql('ARRAY_AGG(tags.id ORDER BY taggings.created_at ASC) AS setting_ids, ARRAY_AGG(tags.name ORDER BY taggings.created_at ASC)')
    settings = settings.pluck(:id, sql)
    settings.map{ |i| [i[0], i[1].zip(i[2])] }.to_h
  end

  def characters_list(characters, show_template)
    characters = characters.left_outer_joins(:template) if show_template
    attributes = [:id, :name, :template_name, :screenname, :pb, :user_id, 'users.username', Arel.sql('users.deleted as user_deleted')]
    attributes += ['templates.id', 'templates.name'] if show_template
    characters.joins(:user).pluck(*attributes)
  end
end

app/views/characters/_icon_view.haml
- if @template.nil? && name.present?
  %tr
    %td.subber.padding-10{colspan: 6}
      - if name.is_a? String
        %b= name
        - if local_assigns[:show_new_character_button]
          = link_to new_character_path do
            .link-box.action-new{style: 'font-size: 14px'} + New Character
      - else
        %b
          Template:
          = link_to name.name, template_path(name)
        - if current_user.try(:id) == name.user_id
          = link_to new_character_path(template_id: name.id) do
            .link-box.action-new{style: 'font-size: 14px'} + New Instance
          = link_to edit_template_path(name) do
            .link-box.action-edit{style: 'font-size: 14px'}
              = image_tag "icons/pencil.png", class: 'vmid', alt: ''
              Edit
          = link_to template_path(name), method: :delete, data: { confirm: 'Are you sure you want to delete this template?' } do
            .link-box.action-delete{style: 'font-size: 14px'} x Delete
- if @template && @template.description.present?
  %tr
    %td.single-description.written-content{colspan: 6}= sanitize_written_content(@template.description)
- elsif @template.nil? && name.present? && name.is_a?(::Template) && name.description.present?
  %tr
    %td.single-description.written-content{colspan: 6}= sanitize_written_content(name.description)
%tr
  %td.icons-box.left-align
    .character-icon-list
      - characters.left_outer_joins(:default_icon).pluck(:id, :name, :screenname, :user_id, :url, :keyword).each do |plucked|
        - char_id, char_name, screenname, user_id, url, keyword = plucked
        .character-icon-item
          = link_to character_path(char_id) do
            - if url
              = icon_mem_tag(url, keyword)
            - else
              .icon.character-no-icon &nbsp;
            .character-name= char_name
            - if screenname
              .character-screenname= surround('(', ')') { breakable_text(screenname) }
          - if Character.deletable_by?(current_user, user_id)
            .delete-button{ id: char_id }
              = link_to '×', character_path(char_id), :method => :delete, data: { confirm: 'Are you sure you want to delete '+char_name+'?' }
      - unless characters.present?
        .centered — No characters yet —

app/views/characters/_list_section.haml
- col_count = 6
- col_count += 1 if local_assigns[:show_template]
- if @template.nil? && name.present?
  %tr
    %td.subber.character-list-template{colspan: col_count}
      - if name.is_a? String
        %b= name
        - if local_assigns[:show_new_character_button]
          = link_to new_character_path do
            .link-box.action-new{style: 'font-size: 14px'} + New Character
      - else
        %b
          Template:
          = link_to name.name, template_path(name)
        - if current_user.try(:id) == name.user_id
          = link_to new_character_path(template_id: name.id) do
            .link-box.action-new{style: 'font-size: 14px'} + New Instance
          = link_to edit_template_path(name) do
            .link-box.action-edit{style: 'font-size: 14px'}
              = image_tag "icons/pencil.png", class: 'vmid', alt: ''
              Edit
          = link_to template_path(name), method: :delete, data: { confirm: 'Are you sure you want to delete this template?' } do
            .link-box.action-delete{style: 'font-size: 14px'} x Delete
- if @template && @template.description.present?
  %tr
    %td.single-description.written-content{colspan: col_count}= sanitize_written_content(@template.description)
- elsif @template.nil? && name.present? && name.is_a?(::Template) && name.description.present?
  %tr
    %td.single-description.written-content{colspan: col_count}= sanitize_written_content(name.description)
- if characters.empty?
  %tr
    %td.centered.padding-5{class: cycle('even', 'odd'), colspan: col_count} — No characters yet —
- else
  %tr
    - klass = cycle('even', 'odd')
    %td.padding-5{class: klass}
      %b Name
    - if local_assigns[:show_template]
      %td.padding-5{class: klass}
        %b Template
    %td.padding-5{class: klass}
      %b Nickname
    %td.padding-5{class: klass}
      %b Screenname
    %td.padding-5{class: klass}
      %b Facecast
    %td.padding-5{class: klass}
      - if local_assigns[:show_user]
        %b User
      - else
        %b Setting
    %td.padding-5{class: klass}
  - settings = settings_info(characters) unless local_assigns[:show_user]
  - pluck = characters_list(characters.ordered, local_assigns[:show_template])
  - pluck.each do |plucked|
    - char_id, char_name, nickname, screenname, pb, user_id, username, user_deleted = plucked
    - if local_assigns[:show_template]
      - template_id, template_name = plucked[-2..]
    - klass = cycle('even', 'odd')
    %tr
      %td.padding-5{class: klass}
        = link_to char_name, character_path(char_id)
      - if local_assigns[:show_template]
        %td.padding-5{class: klass}
          - if template_id.present?
            = link_to template_name, template_path(template_id)
      %td.padding-5{class: klass, style: 'width:15%'}= nickname
      %td.padding-5{class: klass, style: 'width:15%'}= breakable_text(screenname)
      %td.padding-5{class: klass, style: 'width:20%'}= pb
      %td.padding-5{class: klass, style: 'width:15%'}
        - if local_assigns[:show_user]
          = user_mem_link(user_id, username, user_deleted)
        - else
          - setting_links = settings.fetch(char_id, []).map { |setting| link_to(setting[1], tag_path(setting[0])) }
          = safe_join(setting_links, ', ')

      %td.width-70.right-align{class: klass}
        - unless local_assigns[:hide_buttons]
          - if Character.editable_by?(current_user, user_id)
            = link_to edit_character_path(char_id) do
              = image_tag "icons/pencil.png", alt: 'Edit'
          - if Character.deletable_by?(current_user, user_id)
            = link_to character_path(char_id), :method => :delete, data: { confirm: "Are you sure you want to delete #{char_name}?" } do
              = image_tag "icons/cross.png", alt: 'Delete'
            &nbsp;
  - if characters.methods.include?(:total_pages) && characters.total_pages > 1
    %tfoot
      %tr
        %td{colspan: col_count}= render 'posts/paginator', paginated: characters

app/views/characters/edit.haml
- content_for :breadcrumbs do
  = link_to "Characters", user_characters_path(current_user)
  &raquo;
  - if @character.template.try(:persisted?)
    = link_to @character.template.name, template_path(@character.template)
    &raquo;
  = link_to @character.name, character_path(@character)
  &raquo;
  %b Edit

= form_for @character, url: character_path(@character), method: :put do |f|
  .character-form
    %table.form-table
      %thead
        %tr
          %th.editor-title{colspan: 2}= @character.name
      = render 'editor', f: f

    %br
    %table.form-table
      %thead
        %tr
          %th.editor-title
            Aliases and Pseudonyms
            - if @character.user_id == current_user.id
              = link_to new_character_alias_path(@character) do
                .link-box.action-new + New Alias
      %tbody
        - @aliases.each do |calias|
          %tr
            %td.padding-5{class: cycle('even', 'odd')}
              = calias.name
              - if @character.user_id == current_user.id
                .float-right
                  = link_to character_alias_path(@character, calias), method: :delete, confirm: 'Are you sure you want to delete this alias?' do
                    = image_tag "icons/cross.png", alt: 'Delete'
        - if @aliases.empty?
          %tr
            %td.centered.padding-10{ class: cycle('even', 'odd'), colspan: 6 } — No aliases yet —

  = render 'icon_selector'

app/views/characters/new.haml
= form_for @character, url: characters_path, method: :post do |f|
  = f.hidden_field :default_icon_id
  .character-form
    %table.form-table
      %thead
        %tr
          %th.editor-title{colspan: 2} New Character
      = render 'editor', f: f

  = render 'icon_selector'

app/views/characters/replace.haml
- content_for :breadcrumbs do
  = link_to "Characters", user_characters_path(current_user)
  - if @character.template
    &raquo;
    = link_to @character.template.name, template_path(@character.template)
  &raquo;
  = link_to @character.name, character_path(@character)
  &raquo;
  %b Replace

- content_for :disclaimer do
  %tr
    %td.odd.centered{colspan: 2}
      .details *This does NOT replace icons*

- content_for :aliases do
  - if @character.aliases.exists?
    = select_tag :orig_alias, options_for_select({'— Any Alias —': 'all'}, 'all') + options_from_collection_for_select(@character.aliases, :id, :name), prompt: '— No alias —'

- content_for :options do
  = select_tag :icon_dropdown, options_for_select(@alt_dropdown, @alt.try(:id)), prompt: "No Character"
  = select_tag :alias_dropdown, options_from_collection_for_select(@alt.try(:aliases), :id, :name), prompt: '— No alias —', class: ('hidden' unless @alt.try(:aliases).present?)

= form_for @character, url: do_replace_character_path(@character), method: :post do
  = render 'global/replace', obj: @character, name: @character.name, icon: @character.default_icon, alt_icon: @alts.first.try(:default_icon), is_character: true

app/views/characters/show.haml
- content_for :breadcrumbs do
  - if @character.user_id == current_user.try(:id)
    = link_to "Characters", user_characters_path(current_user)
  - else
    = user_link(@character.user)
    - unless @character.user.deleted?
      &raquo;
      = link_to "#{@character.user.username}'s Characters", user_characters_path(@character.user)
  - if @character.template
    &raquo;
    = link_to @character.template.name, template_path(@character.template)
  &raquo;
  = link_to_if params[:view].present?, @character.name, character_path(@character)
  &raquo;
  - if params[:view] == 'galleries'
    %b Galleries
  - elsif params[:view] == 'posts'
    %b Posts
  - else
    %b Info

%table.left-info-box.character-info-box
  %thead
    %tr
      %th.info-box-header
        %span.character-name= @character.name
        - if @character.screenname
          %br
          %span.character-screenname= breakable_text(@character.screenname)
  %tbody
    - if @character.default_icon
      %tr
        %td.character-icon.icons-box
          = link_to icon_path(@character.default_icon) do
            = icon_tag @character.default_icon
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to character_path(@character) do
          = image_tag "icons/chart_bar.png", alt: ''
          Info
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to character_path(@character, view: 'galleries') do
          = image_tag "icons/photos.png", alt: ''
          Galleries
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to character_path(@character, view: 'posts') do
          = image_tag "icons/book_open.png", alt: ''
          Posts
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to search_replies_path(commit: true, character_id: @character.id) do
          = image_tag "icons/table_multiple.png", alt: ''
          Replies
    - if @character.editable_by?(current_user)
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to edit_character_path(@character), class: 'character-edit' do
            = image_tag "icons/pencil.png", alt: ''
            Edit Character
    - if logged_in? && @character.user_id == current_user.id
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to duplicate_character_path(@character), method: :post, class: 'character-duplicate', data: { confirm: 'Are you sure you want to duplicate this character?' } do
            = image_tag "icons/arrow_branch.png", alt: ''
            Duplicate Character
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to replace_character_path(@character), class: 'character-replace' do
            = image_tag "icons/swap.png", style: 'width: 16px;', alt: ''
            Replace Character
    - if @character.deletable_by?(current_user)
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to character_path(@character), method: :delete, class: 'character-delete', data: { confirm: 'Are you sure you want to delete this character?' } do
            = image_tag "icons/cross.png", alt: ''
            Delete Character

- if params[:view] == 'galleries'
  - galleries = @character.galleries.ordered
  %table.character-right-content-box#reorder-galleries-table
    %thead
      %tr
        %th.table-title
          Galleries
          #loading.float-right.hidden= loading_tag
          #saveerror.float-right.hidden
            = image_tag "icons/exclamation.png", title: 'Error', class: 'vmid', alt: '!'
            Error, please refresh
          .saveconf.float-right.hidden
            = image_tag "icons/accept.png", title: 'Saved', class: 'vmid', alt: ''
            Saved
    - galleries.each do |gallery|
      = render 'galleries/single', gallery: gallery, klass: 'subber', skip_forms: true, character_gallery: gallery.character_gallery_for(@character), is_owner: @character.user == current_user
    - unless galleries.present?
      %tbody
        %tr
          %td.icon-box
            .centered.padding-5 — No galleries yet —
- elsif params[:view] == 'posts'
  - content_for :posts_title do 'Recent Threads' end
  = render 'posts/list', posts: @posts, table_class: 'character-right-content-box'
- else
  - reset_cycle
  %table.character-right-content-box
    %thead
      %tr
        %th.table-title{colspan: 2} Info
    %tbody
      - nicknames = ([@character.template_name] + @character.aliases.ordered.pluck(:name)).compact
      - if nicknames.present?
        %tr
          %th.sub.vtop.width-150 Nickname(s)
          %td.character-template-nickname{class: cycle('even', 'odd')}= nicknames.join(", ")
      - if @character.template
        %tr
          %th.sub.vtop.width-150 Template
          %td.character-template{class: cycle('even', 'odd')}
            = link_to @character.template.name, template_path(@character.template), class: 'character-template'
      %tr
        %th.sub.vtop.width-150 Facecast
        %td.character-pb{class: cycle('even', 'odd')}= @character.pb
      - if @character.settings.present?
        %tr
          %th.sub.vtop.width-150 Setting
          - setting_links = @character.settings.map { |setting| link_to(setting.name, tag_path(setting)) }
          %td.character-setting{class: cycle('even', 'odd')}= safe_join(setting_links, ', ')
      - if @character.description
        %tr
          %th.sub.vtop.width-150 Description
          %td.character-description.written-content{class: cycle('even', 'odd')}= sanitize_written_content(@character.description)