config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/confirm_tos' => 'sessions#confirm_tos', as: :confirm_tos, via: :patch
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users, except: :destroy do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      get :search
    end
    member do
      put :password
      get :output
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index do
    collection { get :search}
  end
  resources :characters do
    resources :aliases, only: [:new, :create, :destroy]
    member do
      get :replace
      post :do_replace
      post :duplicate
    end
    collection do
      get :search
      get :facecasts
    end
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
    collection { get :search}
  end

  # Forums
  resources :boards do
    collection do
      post :mark
      get :search
    end
  end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :delete_history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member do
      get :history
      post :restore
    end
    collection { get :search }
  end
  resources :tags, except: [:new, :create]

  # Indexes
  resources :indexes
  resources :index_sections, except: [:index]
  resources :index_posts, only: [:new, :create, :edit, :update, :destroy]

  # Blocks
  resources :blocks, except: [:show]

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index, :show] do
        member { get :posts }
      end
      resources :board_sections, only: [] do
        collection { post :reorder }
      end
      resources :characters, only: [:index, :show, :update] do
        collection { post :reorder }
      end
      resources :galleries, only: :show
      resources :icons, only: [] do
        collection { post :s3_delete }
      end
      resources :index_posts, only: [] do
        collection { post :reorder }
      end
      resources :index_sections, only: [] do
        collection { post :reorder }
      end
      resources :posts, only: [:index, :show] do
        resources :replies, only: :index
        collection { post :reorder }
      end
      resources :tags, only: [:index, :show]
      resources :templates, only: :index
      resources :users, only: :index do
        member { get :posts }
      end
    end
  end

  # Legalese
  match '/tos' => 'about#tos', as: :tos, via: :get
  match '/privacy' => 'about#privacy', as: :privacy, via: :get
  match '/contact' => 'about#contact', as: :contact, via: :get
  match '/dmca' => 'about#dmca', as: :dmca, via: :get

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :news
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount Resque::Server.new, :at => "/resque_web"
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
  has_many :post_tags, inverse_of: :tag
  has_many :character_tags, inverse_of: :tag
  has_many :gallery_tags, inverse_of: :tag

  has_many :child_taggings, class_name: 'ActsAsTaggableOn::Tagging', dependent: :destroy

  has_many :owners, through: :child_taggings, source: :taggable, source_type: 'User', dependent: :destroy
  has_many :posts, through: :child_taggings, source: :taggable, source_type: "Post", dependent: :destroy
  has_many :characters, through: :child_taggings, source: :taggable, source_type: "Character", dependent: :destroy

  TYPES = %w(ContentWarning Label Setting GalleryGroup)

  validates :name, uniqueness: { scope: :type }

  scope :ordered_by_type, -> { order(type: :desc, name: :asc) }

  scope :ordered_by_name, -> { order(name: :asc) }

  scope :ordered_by_id, -> { order(id: :asc) }

  scope :ordered_by_tagging, -> { order('tagging.created_at ASC') }


  # rubocop:disable Style/TrailingCommaInArguments
  scope :with_item_counts, -> {
    select(
      <<~SQL
        (SELECT COUNT(DISTINCT taggings.taggable_id) FROM taggings WHERE taggings.tag_id = tags.id AND taggings.taggable_type = 'Post') AS post_count,
        (SELECT COUNT(DISTINCT taggings.taggable_id) FROM taggings WHERE taggings.tag_id = tags.id AND taggings.taggable_type = 'Character') AS character_count
      SQL
    )
  }
  # rubocop:enable Style/TrailingCommaInArguments

  def editable_by?(user)
    return false unless user
    return true if deletable_by?(user)
    return true if user.has_permission?(:edit_tags)
    return false unless is_a?(Setting)
    !owners.exists?
  end

  def deletable_by?(user)
    return false unless user
    return true if user.has_permission?(:delete_tags)
    owner_ids.include?(user.id)
  end

  def as_json(options={})
    tag_json = {id: self.id, text: self.name}
    return tag_json unless options[:include].present?
    if options[:include].include?(:gallery_ids)
      g_tags = ActsAsTaggableOn::Tagging.where(taggable_type: 'Gallery').joins('INNER JOIN galleries ON galleries.id = taggings.taggable_id')
      g_tags = g_tags.where(galleries: {user_id: options[:user_id]}) if options[:user_id].present?
      tag_json[:gallery_ids] = g_tags.pluck('galleries.id')
    end
    tag_json
  end

  def id_for_select
    return id if persisted? # id present on unpersisted records when associated record is invalid
    "_#{name}"
  end

  def post_count
    return read_attribute(:post_count) if has_attribute?(:post_count)
    posts.count
  end

  def character_count
    return read_attribute(:character_count) if has_attribute?(:character_count)
    characters.count
  end

  def gallery_count
    return read_attribute(:gallery_count) if has_attribute?(:gallery_count)
    galleries.count
  end

  def has_items?
    # TODO auto destroy when false, and also maybe fix with settings/canons
    post_count + character_count + gallery_count > 0
  end

  def merge_with(other_tag)
    transaction do
      PostTag.where(tag_id: other_tag.id).where(post_id: post_tags.select(:post_id).distinct.pluck(:post_id)).delete_all
      PostTag.where(tag_id: other_tag.id).update_all(tag_id: self.id)
      CharacterTag.where(tag_id: other_tag.id).where(character_id: character_tags.select(:character_id).distinct.pluck(:character_id)).delete_all
      CharacterTag.where(tag_id: other_tag.id).update_all(tag_id: self.id)
      GalleryTag.where(tag_id: other_tag.id).where(gallery_id: gallery_tags.select(:gallery_id).distinct.pluck(:gallery_id)).delete_all
      GalleryTag.where(tag_id: other_tag.id).update_all(tag_id: self.id)
      TagTag.where(tag_id: other_tag.id, tagged_id: self.id).delete_all
      TagTag.where(tag_id: self.id, tagged_id: other_tag.id).delete_all
      TagTag.where(tag_id: other_tag.id).update_all(tag_id: self.id)
      TagTag.where(tagged_id: other_tag.id).update_all(tagged_id: self.id)
      other_tag.destroy
    end
  end

  # AATO overrides
  def self.for_context(context)
    where(type: context.classify)
  end

  # overrides the complicated thing AATO does because their column isn't citext
  def self.named(name)
    where(name: name)
  end

  def self.named_any(list)
    where(name: list)
  end

  def self.named_like(name)
    where('name LIKE ?', sanitize_sql_like(name))
  end

  def self.named_like_any(list)
    where('name LIKE ?', sanitize_sql_like(list))
  end

  def self.find_or_create_all_with_like_by_name(*list)
    list = Array(list).flatten

    return [] if list.empty?

    list.map do |tag_name|
      existing_tag = self.find_by(name: tag_name)
      existing_tag || create!(name: tag_name)
    end
  end

  private

  # disables the AATO unscoped uniqueness validation
  def validates_name_uniqueness?
    false
  end
end

app/controllers/api/v1/tags_controller.rb
class Api::V1::TagsController < Api::ApiController
  before_action :find_tag, except: :index

  resource_description do
    description 'Viewing tags'
  end

  api :GET, '/tags', 'Load all the tags of the specified type that match the given query, results ordered by name'
  param :q, String, required: false, desc: "Query string"
  param :page, :number, required: false, desc: 'Page in results (25 per page)'
  param :t, Tag::TYPES, required: true, desc: 'Type of the tag to search'
  param :user_id, :number, required: false, desc: 'Filter GalleryGroups to the current user'
  param :tag_id, :number, required: false, desc: 'Used for settings so we don\'t show the current setting as a possible parent setting of itself'
  error 422, "Invalid parameters provided"
  def index
    type = find_type
    queryset = type.where("name LIKE ?", params[:q].to_s + '%').ordered_by_name

    # gallery groups only searches groups the specified user has used
    if (user_id = params[:user_id]) && type == GalleryGroup
      user_gal_tags = GalleryGroup.joins(:galleries).where(galleries: {user_id: user_id}).pluck(:id)
      user_char_tags = GalleryGroup.joins(:characters).where(characters: {user_id: user_id}).pluck(:id)
      queryset = queryset.where(id: user_gal_tags + user_char_tags)
    end

    queryset = queryset.where.not(id: params[:tag_id]) if type == Setting && params[:tag_id].present?

    tags = paginate queryset, per_page: 25
    render json: {results: tags}
  end

  api :GET, '/tags/:id', 'Load a single tag as a JSON resource'
  param :id, :number, required: true, desc: 'Tag ID'
  error 404, "Tag not found"
  def show
    render json: @tag.as_json(include: [:gallery_ids], user_id: params[:user_id])
  end

  private

  def find_tag
    unless (@tag = Tag.find_by(id: params[:id]))
      error = {message: 'Tag could not be found'}
      render json: {errors: [error]}, status: :not_found and return
    end
    @tag = find_type(@tag.type).find_by(id: params[:id])
  end

  def find_type(type_string=nil)
    type_string ||= params[:t]
    Tag::TYPES.detect {|x| x == type_string }.constantize
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true
class TagsController < ApplicationController
  before_action :login_required, except: [:index, :show]
  before_action :find_tag, except: :index
  before_action :permission_required, except: [:index, :show, :destroy]

  def index
    @tags = TagSearcher.new.search(tag_name: params[:name], tag_type: params[:view], page: page)
    @view = params[:view]
    @page_title = @view.present? ? @view.titlecase.pluralize : 'Tags'
    @tag_options = (Tag::TYPES - ['GalleryGroup']).sort.reverse.map{|t| [t.titlecase, t]}.to_h
    use_javascript('tags/index')
  rescue InvalidTagType => e
    flash[:error] = e.api_error
    redirect_to tags_path
  end

  def show
    @page_title = @tag.name.to_s
    @view = params[:view]
    @meta_og = og_data

    if @view == 'posts'
      @posts = posts_from_relation(@tag.posts.ordered)
    elsif @view == 'characters'
      @characters = @tag.characters.includes(:user, :template).ordered.paginate(per_page: 25, page: page)
    elsif @view == 'galleries'
      @galleries = @tag.galleries.with_icon_count.ordered_by_name
      use_javascript('galleries/expander')
    elsif @view != 'settings'
      @view = 'info'
    end
  end

  def edit
    @page_title = "Edit Tag: #{@tag.name}"
    build_editor
  end

  def update
    @tag.assign_attributes(tag_params)

    begin
      Tag.transaction do
        assign_owners
        assign_children
        @tag.save!
      end
    rescue ActiveRecord::RecordInvalid
      flash.now[:error] = {
        message: "Tag could not be saved because of the following problems:",
        array: @tag.errors.full_messages
      }
      @page_title = "Edit Tag: #{@tag.name}"
      build_editor
      render :edit
    else
      flash[:success] = "Tag saved!"
      redirect_to tag_path(@tag)
    end
  end

  def destroy
    unless @tag.deletable_by?(current_user)
      flash[:error] = "You do not have permission to edit this tag."
      redirect_to tag_path(@tag) and return
    end

    begin
      @tag.destroy!
    rescue ActiveRecord::RecordNotDestroyed
      flash[:error] = {
        message: "Tag could not be deleted.",
        array: @tag.errors.full_messages
      }
      redirect_to tag_path(@tag)
    else
      flash[:success] = "Tag deleted."

      url_params = {}
      url_params[:page] = page if params[:page].present?
      url_params[:view] = params[:view] if params[:view].present?
      redirect_to tags_path(url_params)
    end
  end

  private

  def find_tag
    unless (@tag = Tag.find_by(id: params[:id]))
      flash[:error] = "Tag could not be found."
      redirect_to tags_path
    end
  end

  def permission_required
    unless @tag.editable_by?(current_user)
      flash[:error] = "You do not have permission to edit this tag."
      redirect_to tag_path(@tag)
    end
  end

  def build_editor
    return unless @tag.is_a?(Setting)
    use_javascript('tags/edit')
  end

  def og_data
    desc = []
    desc << generate_short(@tag.description) if @tag.description.present?
    stats = []
    post_count = @tag.posts.where(privacy: Concealable::PUBLIC).count
    stats << "#{post_count} " + "post".pluralize(post_count) if post_count > 0
    if @tag.is_a?(GalleryGroup)
      gallery_count = @tag.galleries.count
      stats << "#{gallery_count} " + "gallery".pluralize(gallery_count) if gallery_count > 0
    end
    character_count = @tag.characters.count
    stats << "#{character_count} " + "character".pluralize(character_count) if character_count > 0
    desc << stats.join(', ')
    title = [@tag.name]
    title << @tag.owners.map(&:username).join(', ') if @tag.owners.exists?
    title << @tag.class.to_s.titleize
    {
      url: tag_url(@tag),
      title: title.join(' · '),
      description: desc.join("\n"),
    }
  end

  def assign_owners
    owner_ids = params.fetch(:tag, {})[:owner_ids]
    return unless owner_ids.present?
    owner_ids -= @tag.owner_ids
    owner_ids.each { |owner_id| ActsAsTaggableOn::Tagging.create(taggable_type: 'User', taggable_id: owner_id, tag: @tag, context: 'settings') }
  end

  def assign_children
    children_ids = params.fetch(:tag, {})[:children_ids]
    return unless children_ids.present?
    children_ids -= @tag.children_ids
    children_ids.each do |owner_id|
      ActsAsTaggableOn::Tagging.create(taggable_type: 'ActsAsTaggableOn::Tag', taggable_id: owner_id, tag: @tag, context: 'settings')
    end
  end

  def tag_params
    permitted = [:type, :description, :owned]
    if current_user.admin? || @tag.owners.include?(current_user)
      permitted << :name
      permitted << {setting_list: []} if @tag.is_a?(Setting)
    end
    params.fetch(:tag, {}).permit(permitted)
  end
end

app/helpers/tag_helper.rb
module TagHelper
  def delete_path(tag)
    url_params = {}
    url_params[:page] = page if params[:page].present?
    url_params[:view] = @view if @view.present?
    tag_path(tag, url_params)
  end

  def tag_select(obj, form, assoc, opts={})
    attr_name = assoc.to_s.singularize + "_ids"
    preview_collection = instance_variable_get("@#{assoc}")

    collection = if preview_collection.nil? # if I used || it would skip []s
      obj.send(assoc) # form.object != obj
    else
      preview_collection
    end
    selected_ids = collection.map(&:id_for_select)

    form.select(
      attr_name,
      options_from_collection_for_select(collection, :id_for_select, :name, selected_ids),
      {},
      {multiple: true}.merge(opts),
    )
  end
end

app/views/tags/_characters.haml
%table.tag-right-content-box
  %thead
    %tr
      %th.table-title{colspan: 7} Characters Tagged: #{@tag.name}
  %tbody
    = render 'characters/list_section', name: nil, characters: @characters, hide_buttons: true, show_user: true, show_template: true

app/views/tags/_editor.haml
%tbody
  %tr
    %th.sub Name
    %td{class: cycle('even', 'odd')}
      - if current_user.admin? || f.object.user_id == current_user.id
        = f.text_field :name, placeholder: "Tag Name", class: 'text'
      - else
        = f.object.name
  %tr
    %th.sub Owner
    %td{class: cycle('even', 'odd')}
      - if current_user.admin? || f.object.user_id == current_user.id
        = f.select :user_id, options_from_collection_for_select(User.ordered.active, :id, :username, f.object.user_id), {}, {class: 'chosen-select'}
      - else
        = user_link(f.object.user)
  %tr
    %th.sub Owned?
    %td{class: cycle('even', 'odd')}
      = f.check_box :owned, class: 'optionbox'
      = f.label :owned, 'Tag belongs to owner'
  - if f.object.is_a?(Setting)
    %tr
      %th.sub Parent Settings
      %td{class: cycle('even', 'odd')}= tag_select(@tag, f, :parent_settings, data: {tag_id: f.object.id})
    %tr
      %th.sub.vtop Description
      %td{class: cycle('even', 'odd')}= f.text_area :description, placeholder: 'Description', cols: 35
%tfoot
  %tr
    %th.form-table-ender{colspan: 2}= submit_tag "Save", class: 'button'

app/views/tags/_galleries.haml
%table.tag-right-content-box
  %thead
    %tr
      %th.table-title{colspan: 4} Galleries Tagged: #{@tag.name}
  %tbody
    - if @galleries.present?
      = render partial: 'galleries/expandable', collection: @galleries, as: :gallery, locals: {tag: @tag}
    - else
      %td.centered.padding-5{class: cycle('even', 'odd'), colspan: 4} — No galleries yet —

app/views/tags/_info.haml
%table.tag-right-content-box
  %thead
    %tr
      %th.table-title{colspan: 2} Info
  %tbody
    - if @tag.is_a?(Setting) && @tag.parents.present?
      %tr
        %th.sub.centered.width-150= 'Parent Setting'.pluralize(@tag.parents.count)
        - setting_links = @tag.parents.map { |c| link_to(c.name, tag_path(c))}
        %td{class: cycle('even', 'odd')}= safe_join(setting_links, ', ')
    - if @tag.is_a?(Setting)
      %tr
        %th.sub.centered.width-150 Owner
        - if @tag.owners.exists?
          = safe_join(@tag.owners.map { |user| user_link(user) }, ', ')
        - else
          %td{class: cycle('even', 'odd'), title: ('This setting is not marked as owned')}
    - if @tag.description.present?
      %tr
        %th.sub.centered.width-150.vtop Description
        %td.written-content{class: cycle('even', 'odd')}= sanitize_written_content(@tag.description)

app/views/tags/_posts.haml
- content_for :posts_title do
  Posts Tagged: #{@tag.name}

= render 'posts/list', posts: @posts, table_class: 'tag-right-content-box'

app/views/tags/_settings.haml
%table.tag-right-content-box
  %thead
    %tr
      %th.table-title{colspan: 6} Settings Tagged: #{@tag.name}
  %tbody
    - @tag.children.each do |setting|
      %tr
        %td{class: cycle('even', 'odd')}= link_to setting.name, tag_path(setting)

app/views/tags/edit.haml
- content_for :breadcrumbs do
  = link_to "Tags", tags_path
  &raquo;
  = link_to @tag.type.pluralize.titlecase, tags_path(view: @tag.type)
  &raquo;
  = link_to @tag.name, tag_path(@tag)
  &raquo;
  %b Edit

= form_for @tag.becomes(Tag) do |f|
  - f.object = @tag.becomes(@tag.class) # handles the STI with Tag/Setting/ContentWarning properly
  %table.form-table
    %thead
      %tr
        %th.editor-title{colspan: 2} Edit #{@tag.type.titlecase}
    = render 'editor', f: f

app/views/tags/index.haml
- col_count = 4
- col_count += 1 unless @view.present?
- col_count += 1 if @view == 'Setting'

- if @view.present?
  - content_for :breadcrumbs do
    = link_to "Tags", tags_path
    &raquo;
    %b= @view.pluralize.titlecase

%table
  %thead
    %tr
      %th.table-title{colspan: col_count}
        = @view.present? ? @view.titlecase.pluralize : 'Tags'
    %tr
      %th.subber.padding-10{colspan: col_count}
        = form_tag tags_path, method: :get do
          Search for a tag:
          = text_field_tag :name, params[:name], id: 'tag-search-name', placeholder: 'Exact name (case-insensitive)'
          = select_tag :view, options_for_select(@tag_options, @view), include_blank: '— Choose Type —', id: 'tag-view'
          = submit_tag "Search", class: 'button', id: 'tag-search'
    %tr
      %th.sub Name
      - unless @view.present?
        %th.sub Type
      - if @view == 'Setting'
        %th.sub Owners
      %th.sub Posts
      %th.sub Characters
      %th.sub
  %tbody
    - @tags.each do |tag|
      - klass = cycle('even', 'odd')
      %tr
        %td{class: klass}= link_to tag.name, tag_path(tag)
        - unless @view.present?
          %td{class: klass}= link_to tag.type.titlecase, tags_path(view: tag.type)
        - if @view == 'Setting'
          %td{class: klass}
            - if tag.owners.exists?
              = safe_join(tag.owners.map { |user| user_link(user) }, ', ')
            - else
              None
        %td{class: klass}= tag.post_count
        %td{class: klass}= tag.character_count
        %td.width-70.right-align{class: klass}
          - if tag.editable_by?(current_user)
            = link_to edit_tag_path(tag) do
              = image_tag "icons/pencil.png", alt: 'Edit'
          - if tag.deletable_by?(current_user)
            = link_to delete_path(tag), method: :delete, data: { confirm: 'Are you sure you want to delete '+tag.name+'?' } do
              = image_tag "icons/cross.png", alt: 'Delete'
            &nbsp;
    - if @tags.empty?
      %tr
        %td.centered.padding-10{ class: cycle('even', 'odd'), colspan: col_count } — No matching tags —
  - if @tags.total_pages > 1
    %tfoot
      %tr
        %td{colspan: 6}= render 'posts/paginator', paginated: @tags

app/views/tags/show.haml
- content_for :breadcrumbs do
  = link_to "Tags", tags_path
  &raquo;
  = link_to @tag.type.pluralize.titlecase, tags_path(view: @tag.type)
  &raquo;
  %b= @tag.name

%table.left-info-box.tag-info-box
  %thead
    %tr
      %th.info-box-header
        %span.character-name #{@tag.type.titlecase}: #{@tag.name}
  %tbody
    %tr
      %td.centered{class: cycle('even', 'odd')}
        = link_to tag_path(@tag) do
          = image_tag "icons/chart_bar.png", class: 'vmid', alt: ''
          Info
    - if @tag.is_a?(GalleryGroup)
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to tag_path(@tag, view: 'galleries') do
            = image_tag "icons/photos.png", class: 'vmid', alt: ''
            Galleries
    - else
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to tag_path(@tag, view: 'posts') do
            = image_tag "icons/book_open.png", class: 'vmid', alt: ''
            Posts
    - if @tag.is_a?(Setting) || @tag.is_a?(GalleryGroup)
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to tag_path(@tag, view: 'characters') do
            = image_tag "icons/group.png", class: 'vmid', alt: ''
            Characters
    - if @tag.is_a?(Setting) && @tag.children.present?
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to tag_path(@tag, view: 'settings') do
            = image_tag "icons/world.png", class: 'vmid', alt: ''
            Settings
    - if @tag.editable_by?(current_user)
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to edit_tag_path(@tag) do
            = image_tag "icons/pencil.png", class: 'vmid', alt: ''
            Edit #{@tag.type.titlecase}
    - if @tag.deletable_by?(current_user)
      %tr
        %td.centered{class: cycle('even', 'odd')}
          = link_to tag_path(@tag), method: :delete, data: { confirm: 'Are you sure you want to delete this tag?' } do
            = image_tag "icons/cross.png", class: 'vmid', alt: ''
            Delete #{@tag.type.titlecase}

= render @view