config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/confirm_tos' => 'sessions#confirm_tos', as: :confirm_tos, via: :patch
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users, except: :destroy do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      get :search
    end
    member do
      put :password
      get :output
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index do
    collection { get :search}
  end
  resources :characters do
    resources :aliases, only: [:new, :create, :destroy]
    member do
      get :replace
      post :do_replace
      post :duplicate
    end
    collection do
      get :search
      get :facecasts
    end
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
    collection { get :search}
  end

  # Forums
  resources :boards do
    collection do
      post :mark
      get :search
    end
  end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :delete_history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member do
      get :history
      post :restore
    end
    collection { get :search }
  end
  resources :tags, except: [:new, :create]

  # Indexes
  resources :indexes
  resources :index_sections, except: [:index]
  resources :index_posts, only: [:new, :create, :edit, :update, :destroy]

  # Blocks
  resources :blocks, except: [:show]

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index, :show] do
        member { get :posts }
      end
      resources :board_sections, only: [] do
        collection { post :reorder }
      end
      resources :characters, only: [:index, :show, :update] do
        collection { post :reorder }
      end
      resources :galleries, only: :show
      resources :icons, only: [] do
        collection { post :s3_delete }
      end
      resources :index_posts, only: [] do
        collection { post :reorder }
      end
      resources :index_sections, only: [] do
        collection { post :reorder }
      end
      resources :posts, only: [:index, :show] do
        resources :replies, only: :index
        collection { post :reorder }
      end
      resources :tags, only: [:index, :show]
      resources :templates, only: :index
      resources :users, only: :index do
        member { get :posts }
      end
    end
  end

  # Legalese
  match '/tos' => 'about#tos', as: :tos, via: :get
  match '/privacy' => 'about#privacy', as: :privacy, via: :get
  match '/contact' => 'about#contact', as: :contact, via: :get
  match '/dmca' => 'about#dmca', as: :dmca, via: :get

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :news
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount Resque::Server.new, :at => "/resque_web"
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def tos
    @page_title = 'Terms of Service'
  end

  def privacy
    @page_title = 'Privacy Policy'
  end

  def contact
    @page_title = 'Contact Us'
  end

  def dmca
    @page_title = 'DMCA Policy'
  end
end

app/views/about/_accept_tos.haml
- content_for :tos_form do
  %table#signup.form-table
    %thead
      %tr
        %th Accept our Terms of Service
    %tbody
      %tr#terms
        %td.odd
          Our Terms of Service have recently changed!
          Please read and agree to the
          = link_to 'Terms of Service', tos_path
          and the
          = link_to 'Privacy Policy', privacy_path
    %tfoot
      %tr
        %th.form-table-ender{colspan: 2}= submit_tag "I agree to the terms of service", class: 'button', name: :tos_check, id: :tos_check

- if logged_in?
  = form_for current_user, url: user_path(current_user), method: :put, name: :tos_form do
    = content_for :tos_form
- else
  = form_tag confirm_tos_path, method: :patch do
    = content_for :tos_form

app/views/about/accept_tos.haml
= render 'about/accept_tos'

app/views/about/contact.haml
#contact-content.odd{style: 'padding: 15px;'}
  %h1 Contact the Constellation

  %p
    Currently, to contact the Constellation for help or to report a violation of our
    = succeed ',' do
      = link_to 'Terms of Service', tos_path
    you may visit us in the #constellation channel of the
    = link_to "Glowfic Community Discord", Glowfic::DISCORD_LINK_GLOWFIC, target: '_blank', rel: 'noopener'
    or the #general channel of the
    = link_to "Constellation Discord", Glowfic::DISCORD_LINK_CONSTELLATION, target: '_blank', rel: 'noopener'
    or email us at
    = succeed '.' do
      = link_to 'glowfic.constellation@gmail.com', 'mailto:glowfic.constellation@gmail.com'

app/views/about/dmca.haml
#dmca-content.odd{style: 'padding: 15px;'}
  %h1 Glowfic Constellation DMCA Policy

  %h3 Table of Contents

  %ol
    %li= link_to 'Overview', '#overview'
    %li= link_to 'Notification of Copyright Infringement', '#notification'
    %li= link_to 'Takedown Process', '#takedown'
    %li= link_to 'Counter-Notification', '#counter'
    %li= link_to 'Restoration Process', '#restoration'
    %li= link_to 'Repeat Offenses', '#repeats'
    %li= link_to 'Attribution and License', '#license'

  %h3#overview Overview

  %p
    The Digital Millennium Copyright Act (DMCA), and specifically the provisions located at
    = succeed ',' do
      = link_to '17 USC 512', 'http://www.law.cornell.edu/uscode/text/17/512', target: '_blank', rel: 'noopener'
    set forth the steps an online service provider such as the Glowfic Constellation must follow in the event of copyright infringement on their servers.

  %p
    We believe that the DMCA takedown process is a powerful tool that can help copyright holders protect their intellectual property from being exploited.
    We also believe that the DMCA takedown process is a powerful tool that is frequently misused to force a chilling effect on legitimate and legal speech.
    Our enforcement policy is an attempt to prevent the worst abuses of this process that we've seen over the years, while still upholding our legal obligations and protecting copyright holders from the misuse of their intellectual property.

  %p
    This is a complicated process, and the law surrounding it is unclear in many situations. We've tried to make this as readable as possible.
    If you have any questions that aren't covered here, please
    = link_to 'contact us', contact_path
    with your questions.

  %p
    None of this material should be construed as legal advice.
    We cannot advise you on how to protect your rights online, either your rights as a copyright holder or your rights as someone accused of copyright infringement.
    If you are in need of legal advice, contact a lawyer who is licensed to practice in your jurisdiction.

  %h3#notification Notification of Copyright Infringement

  %p
    If you believe that someone on the Glowfic Constellation has violated your copyright, you may send us a Notification of Copyright Infringement.
    For us to process such a notification, it must substantially comply with the requirements set forth in United States law.
    To speed our handling of your notification, please make sure it complies with the following criteria:

  %ol
    %li
      Notifications may be submitted to the Constellation via email (no attachments, please) to
      = succeed '.' do
        %b= link_to 'glowfic.constellation@gmail.com', 'mailto:glowfic.constellation@gmail.com'
    %li
      Notifications must be signed by the copyright holder or the copyright holder's designated agent.
      Signatures may be a physical signature or a digital signature in a recognized industry-standard format such as PGP.
      Unsigned notifications will not be processed.
    %li
      Notifications must specifically identify the copyrighted work being infringed upon.
      For instance, if the work is a published book, provide the title, author, and ISBN;
      if the work is a magazine article, provide the title, author, magazine name, and magazine issue;
      if the work is available on the Internet, provide the URL of the work.
    %li
      Notifications must specifically include the URL where the work is being infringed upon the Constellation's servers.
      For us to be able to reasonably identify the material, you must provide us with the complete URL.
      For instance, provide https://www.glowfic.com/posts/123 (a link to the specific entry).
    %li
      Notifications must include sufficient information for us to contact you, including your address, your telephone number, and your email address.
    %li
      Notifications must contain a statement that you have a good faith belief that the use of the material in this manner is not authorized by the copyright owner(s), their agent, or the law.
    %li
      Notifications must contain a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of the copyright that is allegedly being infringed.

  %p
    Your notification will be forwarded, in its entirety, to the owner of the account posting the allegedly-infringing content.
    We reserve the right to make copies available to third parties, such as the
    = succeed ',' do
      = link_to 'Chilling Effects Clearinghouse', 'http://www.chillingeffects.org/', target: '_blank', rel: 'noopener'
    as we see fit, for purposes of academic study and legal review.

  %h3#takedown Takedown Process

  %p
    When we receive a properly-formatted notice of copyright infringement, we will forward it to the account owner and provide a limited amount of time to disable access to the allegedly-infringing content.

  %p
    If you have received this notice from us, you must delete the entry, comment, or image in question.
    %i Setting an entry's security to Private is not sufficient to qualify as 'disabling access' under the law,
    as this can be undone at any time.

  %p
    If we do not hear back from you within 48 hours, we will delete the content on your behalf.
    This will not affect the rest of your account.

  %p
    You then have one of three choices:

  %ol
    %li
      You can accept the allegation of infringement, and state that you will not restore the content, file a counter-notification, or make further infringement upon the work in the future.
      If you choose to do this, you must delete the entry, comment, or image, if you have not already done so.
      This will count against you for determination of 'repeat offender' status.
      If you do not reply to any of our contact about an alleged infringement within 10 days of our forwarding the notification, we must assume that you have chosen this option.
    %li
      You can state that you do not accept the allegation of infringement, but you do not want to file a counter-notification or have us restore access to the allegedly-infringing content.
      If you choose to do this, we will not restore access to the entry, comment, or image.
      This will not affect the rest of your account.
      This will not count against you for determination of 'repeat offender' status.
    %li
      You can state that you do not accept the allegation of infringement, and let us know that you want to file a counter-notification under the provisions of law.
      If you choose to do this, please see the section below.
      This will not count against you for determination of 'repeat offender' status.

  %p
    If you have received a notice of alleged infringement, you may not re-upload or re-post the allegedly-infringing material, unless you have gone through the counter-notification process.
    This applies whether you have deleted the material yourself, or we deleted the material on your behalf.
    If you do re-upload or re-post the material, we will be forced to entirely disable your account.

  %h3#counter Counter-Notification

  %p
    A counter-notification is a statement, under the provisions of 17 USC 512(g)(3), that you do not believe your content infringes on another person's rights, or that your use of another person's copyrighted material falls into one of the protected categories under law.

  %p
    %i By filing a counter-notification, you are indicating that you are willing to defend your use of the material in court,
    if the copyright owner chooses to bring a lawsuit against you for your use of the material.
    This may involve civil and/or criminal penalties.
    %i We strongly suggest you contact an intellectual property lawyer licensed to practice law in your jurisdiction before you do this,
    so that you are aware of your rights and obligations under the law.

  %p
    There are groups that may help you understand your rights and obligations, including the
    = succeed ',' do
      = link_to 'Chilling Effects Clearinghouse', 'http://www.chillingeffects.org/', target: '_blank', rel: 'noopener'
    the
    = succeed ',' do
      = link_to 'Electronic Frontier Foundation', 'http://www.eff.org/', target: '_blank', rel: 'noopener'
    and the
    = succeed '.' do
      = link_to 'Organization for Transformative Works', 'http://transformativeworks.org/', target: '_blank', rel: 'noopener'
    We are not affiliated with any of these organizations, and they may not be able to help you, but their mission and mandate involves educating people about their rights and obligations under intellectual property law.

  %p
    A counter-notification must contain the following items:

  %ol
    %li
      Your signature. Signatures may be a physical signature or a digital signature in a recognized industry-standard format such as PGP.
    %li
      The URL of your entry, comment, or image that has been called into question.
    %li
      A statement, under penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material.
      This should include any reasons why you believe your use of the material is not infringing.
    %li
      Your name, address, and telephone number.
    %li
      A statement that you consent to the jurisdiction of Federal District Court where you reside, or (if you live outside the United States) that you consent to the jurisdiction of Federal District Court where the Glowfic Constellation is located (currently New York county, New York).
    %li
      A statement that you will accept service of process from the person who provided notification of infringement, or that person's designated agent.

  %p
    Your counter-notification will be provided, in its entirety, to the person who provided notification of alleged infringement.

  %h3#restoration Restoration Process

  %p
    When we receive a counter-notification, we will forward it to the person who made the original notification of alleged infringement.
    From that point, the original notifier has 10 business days after receiving the counter-notification to file an action in court, seeking an injunction against the use of that material.

  %p
    If you have provided us with a notification of infringement, and the user of our service has chosen to file counter-notification, you must inform us that you have filed court action no more than 14 days after we forward the counter-notification to you.
    If you do not, we will re-enable access to the allegedly-infringing material no less than 10 days, and no more than 14 days, after we forward the counter-notification.

  %p
    If you have received a notification of infringement, and you have provided us with your counter-notification, we will re-enable access to the allegedly-infringing material, or let you know that you can re-post the allegedly-infringing material, no less than 10 days, and no more than 14 days, after we have forwarded your counter-notification to the original notifier.

  %p
    If you have filed a counter-notification, you can not re-upload or re-post the allegedly-infringing material until we notify you that the waiting period has expired.
    If you do, we will be forced to entirely disable your account during that time period.

  %h3#repeats Repeat Offenses

  %p
    US law requires us to disable the accounts of repeat offenders of others' copyright.
    What constitutes a repeat offender is not defined by law.

  %p
    We currently define a repeat offender as anyone who has received five valid notifications of copyright infringement.
    Instances where you have filed a counter-notification, or instances where you have indicated that you do not accept the allegation of copyright infringement but do not wish to file a counter-notification, will not count against your account for purposes of determining 'repeat offender' status.
    We reserve the right to alter this definition in the future, at our sole discretion.

  %p
    We also reserve the right to terminate the accounts of those who, in our opinion, misuse or abuse the DMCA notification process against other users.

  %h3#license Attribution and License

  %p
    This DMCA Policy document is based on one developed by Dreamwidth
    = surround '(', ')' do
      = link_to 'https://www.dreamwidth.org/legal/dmca', target: '_blank', rel: 'noopener'
    and is licensed under a Creative Commons Attribution-ShareAlike 2.5 License.

  %p.details Last revised July 8, 2018