config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  apipie

  root :to => 'sessions#index'

  # Accounts
  match '/login' => 'sessions#new', :as => :login, :via => :get
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => :delete
  match '/confirm_tos' => 'sessions#confirm_tos', as: :confirm_tos, via: :patch
  match '/users/:id/templates' => redirect('/users/%{id}/characters'), via: :get
  resources :users, except: :destroy do
    resources :characters, only: :index
    resources :galleries, only: [:index, :show]
    resources :boards, only: :index
    collection do
      get :search
    end
    member do
      put :password
      get :output
    end
  end
  resources :password_resets, only: [:new, :create, :show, :update]

  # Messages and notifications
  resources :messages, except: [:edit, :update, :destroy] do
    collection { post :mark }
  end

  # Characters
  resources :templates, except: :index do
    collection { get :search}
  end
  resources :characters do
    resources :aliases, only: [:new, :create, :destroy]
    member do
      get :replace
      post :do_replace
      post :duplicate
    end
    collection do
      get :search
      get :facecasts
    end
  end

  # Images
  resources :icons, except: [:index, :new, :create] do
    member do
      post :avatar
      get :replace
      post :do_replace
    end
    collection do
      delete :delete_multiple
    end
  end
  resources :galleries do
    member do
      get :add
      post :icon
    end
    collection { get :search}
  end

  # Forums
  resources :boards do
    collection do
      post :mark
      get :search
    end
  end
  resources :board_sections, except: :index
  resources :posts do
    member do
      get :history
      get :delete_history
      get :stats
      post :warnings
    end
    collection do
      post :mark
      get :search
      get :owed
      get :unread
      get :hidden
      post :unhide
    end
  end
  resources :replies, except: [:index, :new] do
    member do
      get :history
      post :restore
    end
    collection { get :search }
  end
  resources :tags, except: [:new, :create]

  # Indexes
  resources :indexes
  resources :index_sections, except: [:index]
  resources :index_posts, only: [:new, :create, :edit, :update, :destroy]

  # Blocks
  resources :blocks, except: [:show]

  # API
  namespace :api do
    namespace :v1 do
      resources :boards, only: [:index, :show] do
        member { get :posts }
      end
      resources :board_sections, only: [] do
        collection { post :reorder }
      end
      resources :characters, only: [:index, :show, :update] do
        collection { post :reorder }
      end
      resources :galleries, only: :show
      resources :icons, only: [] do
        collection { post :s3_delete }
      end
      resources :index_posts, only: [] do
        collection { post :reorder }
      end
      resources :index_sections, only: [] do
        collection { post :reorder }
      end
      resources :posts, only: [:index, :show] do
        resources :replies, only: :index
        collection { post :reorder }
      end
      resources :tags, only: [:index, :show]
      resources :templates, only: :index
      resources :users, only: :index do
        member { get :posts }
      end
    end
  end

  # Legalese
  match '/tos' => 'about#tos', as: :tos, via: :get
  match '/privacy' => 'about#privacy', as: :privacy, via: :get
  match '/contact' => 'about#contact', as: :contact, via: :get
  match '/dmca' => 'about#dmca', as: :dmca, via: :get

  # Miscellaneous
  resources :reports, only: [:index, :show]
  resources :news
  resources :bugs, only: :create
  resources :favorites, only: [:index, :create, :destroy]
  match '/contribute' => 'contribute#index', as: :contribute, via: :get
  mount Resque::Server.new, :at => "/resque_web"
end

app/models/report.rb
# This class is intended to ultimately be used as a parent
# class for both a DailyReport and a MonthlyReport. Until then,
# it does nothing special; see DailyReport.

# TODO consolidate view code; this is not an AR object, so cannot
# use the Viewable concern. This should be abstract enough to work.

class Report < Object
  def self.mark_read(user, at_time)
    view = view_for(user)

    if view.new_record?
      view.read_at = at_time
      return view.save
    end

    return true if at_time <= view.read_at.to_date
    view.read_at = at_time
    view.save!
  end

  def self.last_read(user)
    view_for(user).read_at
  end

  class << self
    protected

    def view_for(user)
      ReportView.where(user_id: user.id).first_or_initialize
    end
  end
end

app/models/report_view.rb
class ReportView < ApplicationRecord
  belongs_to :user, optional: false

  validates :user, uniqueness: true
end

app/controllers/reports_controller.rb
# frozen_string_literal: true
class ReportsController < ApplicationController
  include DateSelectable

  def index
  end

  REPORT_TYPES = ['daily', 'monthly']

  def show
    @report_type = REPORT_TYPES.detect {|x| x == params[:id] }
    unless @report_type
      flash[:error] = "Could not identify the type of report."
      redirect_to reports_path
    end

    @page_title = params[:id].capitalize + " Report"
    @hide_quicklinks = true
    @day = calculate_day

    if logged_in?
      @opened_posts = PostView.where(user_id: current_user.id).select([:post_id, :read_at, :ignored])
      @board_views = BoardView.where(user_id: current_user.id).select([:board_id, :ignored])
      @opened_ids = @opened_posts.map(&:post_id)

      DailyReport.mark_read(current_user, @day) if !current_user.ignore_unread_daily_report? && @day.to_date < Time.zone.now.to_date
    end

    if @report_type == 'daily'
      @posts = DailyReport.new(@day).posts(sort)
      @posts = posts_from_relation(@posts, max: true)
      replies_on_day = Reply.where(created_at: @day.beginning_of_day..@day.end_of_day)
      @reply_counts = replies_on_day.group(:post_id).count
      first_for_day = replies_on_day.order(post_id: :asc, created_at: :asc)
      first_for_day = first_for_day.pluck(Arel.sql('DISTINCT ON (post_id) replies.post_id, replies.id, replies.created_at'))
      first_for_day = first_for_day.to_h { |pluck| [pluck[0], { id: pluck[1], klass: Reply, created_at: pluck[2] }] }
      @link_targets = @posts.to_h{ |post| [post.id, linked_for(post, first_for_day[post.id])] }
    end
  end

  private

  def has_unread?(post)
    return false unless @opened_posts.present?
    view = @opened_posts.detect { |v| v.post_id == post.id }
    return false unless view
    return false if view.ignored?
    return false if view.read_at.nil? # totally unread, not partially
    view.read_at < post.tagged_at
  end
  helper_method :has_unread?

  def never_read?(post)
    return false unless logged_in?
    return true unless @opened_posts.present?
    view = @opened_posts.detect { |v| v.post_id == post.id }
    return true unless view
    return false if view.ignored?
    view.read_at.nil?
  end
  helper_method :never_read?

  def ignored?(post)
    return false unless @opened_posts.present?
    view = @opened_posts.detect { |v| v.post_id == post.id }
    board_view = @board_views.detect { |v| v.board_id == post.board_id }
    return false unless view || board_view
    view.try(:ignored?) || board_view.try(:ignored?)
  end
  helper_method :ignored?

  def linked_for(post, reply)
    if post.created_at.to_date == @day.to_date || reply.nil?
      {id: post.id, klass: Post, created_at: post.created_at}
    else
      reply
    end
  end

  def sort
    @sort ||= case params[:sort]
      when 'subject'
        Arel.sql('LOWER(subject)')
      when 'continuity'
        Arel.sql('LOWER(max(boards.name)), tagged_at desc')
      else
        {first_updated_at: :desc}
    end
  end
  helper_method :sort
end

app/views/reports/_daily.haml
%span.time-loaded{style: 'font-size: 10px; position: absolute; top: 2px; right: 20px;'}= pretty_time(DateTime.now.in_time_zone)

%table
  %thead
    %tr
      %th.table-title{colspan: 7}
        Daily Report -
        = @day.strftime("%b %d, %Y")
        - if @day == Time.zone.today
          %em (Incomplete)
    %tr
      %th.sub{colspan: 7}= render 'date_nav'
    - if @posts.present?
      %tr
        %th.subber.width-15
        %th.subber= link_to 'Thread', url_for(day: params[:day], sort: 'subject')
        %th.subber= link_to 'Continuity', url_for(day: params[:day], sort: 'continuity')
        %th.subber Authors
        %th.subber.width-70 Replies
        %th.subber.width-70 Today
        %th.subber.width-70= link_to 'Updated', url_for(day: params[:day], sort: 'updated')
  - if @posts.present?
    %tbody
      - @posts.each do |post|
        %tr
          - klass = [cycle('even', 'odd')]
          - klass << 'post-ignored' if ignored?(post)
          %td.vtop.post-completed{class: klass.dup.push(post.completed? ? 'post-complete' : 'post-incomplete')}
            - if post.completed?
              = image_tag "icons/book.png", class: 'vmid', title: "Thread Complete", alt: 'Complete'
            - elsif post.on_hiatus?
              = image_tag "icons/hourglass.png", class: 'vmid', title: "Thread On Hiatus", alt: 'Hiatused'
            - elsif post.abandoned?
              = image_tag "icons/book_grey.png", class: 'vmid', title: "Thread Abandoned", alt: 'Abandoned'
            - if !current_user.try(:hide_warnings) && post.has_content_warnings?
              = image_tag "icons/exclamation.png", class: 'vmid', title: "Content Warning: " + post.content_warnings.pluck(:name).join(', '), alt: 'Has Warnings'
            - if post.created_at.beginning_of_day == @day.beginning_of_day
              = image_tag "icons/new.png", class: 'vmid', title: 'New Today', alt: 'New'
          %td.post-subject{class: klass}
            - if has_unread?(post)
              = link_to unread_path(post) do
                = image_tag unread_img, class: 'vmid', title: 'First Unread'
            - if never_read?(post)
              %b= link_to post.subject, post_path(post)
            - else
              = link_to post.subject, post_path(post)
            - if post.description.present?
              %br
              %span.details= sanitize_simple_link_text(post.description)
          %td.vtop.post-board{class: klass}= link_to post.board_name, board_path(post.board_id)
          %td.vtop.post-authors{class: klass}= author_links(post, colored: true)
          %td.vtop.centered.post-replies{class: klass}= link_to post.reply_count, stats_post_path(post)
          %td.vtop.centered.post-replies{class: klass}= link_to @reply_counts[post.id].to_i, post_or_reply_mem_link(**@link_targets[post.id].except(:created_at))
          %td.vtop.centered.post-time{class: klass}= @link_targets[post.id][:created_at].strftime("%l:%M %p")
    %tfoot
      %tr
        %td{colspan: 7}= render 'posts/paginator', paginated: @posts
  - else
    %tr
      %td.centered.even{colspan: 7} — No posts yet —

app/views/reports/_date_nav.haml
- if @day < Time.zone.today
  = link_to url_for(day: @day + 1.day, sort: params[:sort]) do
    - style = 'font-style: italic;' if @day + 1.day >= Time.zone.today
    .view-button{style: style} &raquo; Next Day
= link_to url_for(day: @day - 1.day, sort: params[:sort]) do
  .view-button.float-none &laquo; Previous Day

app/views/reports/_monthly.haml
%span.time-loaded{style: 'font-size: 10px; position: absolute; top: 2px; right: 20px;'}= pretty_time(DateTime.now.in_time_zone)

%table
  %thead
    %tr
      %th.table-title{colspan: 6} Monthly Report
  - 1.upto(1.month.ago.end_of_month.day) do |num_days|
    - day = 1.month.ago.end_of_month - (num_days - 1).days
    - posts = posts_from_relation(Post.where(tagged_at: day.beginning_of_day .. day.end_of_day))
    - if posts.present?
      %tbody
        %tr
          %th.subber{colspan: 6}= day.strftime("%b %d, %Y")
        %tr
          %th.sub.width-15
          %th.sub Thread
          %th.sub Continuity
          %th.sub Authors
          %th.sub Replies
          %th.sub Last Updated
        - posts.each do |post|
          = render 'posts/list_item', post: post, hide_continuity: false

app/views/reports/index.haml
= link_to 'Daily Report', report_path(id: 'daily')
%br
= link_to 'Monthly Report', report_path(id: 'monthly')

app/views/reports/show.haml
= render @report_type